/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as IndexRouteImport } from './index'
import { Route as RoomWelcomeRouteImport } from './room.welcome'
import { Route as RoomCreateRouteImport } from './room.create'
import { Route as RoomRoomIdRouteImport } from './room.$roomId'
import { Route as ProfileSettingsRouteImport } from './profile.settings'
import { Route as ProfileMeRouteImport } from './profile.me'
import { Route as ProfileHistoryRouteImport } from './profile.history'
import { Route as AuthSignupRouteImport } from './auth.signup'
import { Route as AuthLoginRouteImport } from './auth.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomWelcomeRoute = RoomWelcomeRouteImport.update({
  id: '/room/welcome',
  path: '/room/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCreateRoute = RoomCreateRouteImport.update({
  id: '/room/create',
  path: '/room/create',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileMeRoute = ProfileMeRouteImport.update({
  id: '/profile/me',
  path: '/profile/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHistoryRoute = ProfileHistoryRouteImport.update({
  id: '/profile/history',
  path: '/profile/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/me': typeof ProfileMeRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/room/create': typeof RoomCreateRoute
  '/room/welcome': typeof RoomWelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/me': typeof ProfileMeRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/room/create': typeof RoomCreateRoute
  '/room/welcome': typeof RoomWelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/me': typeof ProfileMeRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/room/create': typeof RoomCreateRoute
  '/room/welcome': typeof RoomWelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/profile/history'
    | '/profile/me'
    | '/profile/settings'
    | '/room/$roomId'
    | '/room/create'
    | '/room/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/profile/history'
    | '/profile/me'
    | '/profile/settings'
    | '/room/$roomId'
    | '/room/create'
    | '/room/welcome'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/profile/history'
    | '/profile/me'
    | '/profile/settings'
    | '/room/$roomId'
    | '/room/create'
    | '/room/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ProfileHistoryRoute: typeof ProfileHistoryRoute
  ProfileMeRoute: typeof ProfileMeRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  RoomCreateRoute: typeof RoomCreateRoute
  RoomWelcomeRoute: typeof RoomWelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/welcome': {
      id: '/room/welcome'
      path: '/room/welcome'
      fullPath: '/room/welcome'
      preLoaderRoute: typeof RoomWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/create': {
      id: '/room/create'
      path: '/room/create'
      fullPath: '/room/create'
      preLoaderRoute: typeof RoomCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/me': {
      id: '/profile/me'
      path: '/profile/me'
      fullPath: '/profile/me'
      preLoaderRoute: typeof ProfileMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/history': {
      id: '/profile/history'
      path: '/profile/history'
      fullPath: '/profile/history'
      preLoaderRoute: typeof ProfileHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ProfileHistoryRoute: ProfileHistoryRoute,
  ProfileMeRoute: ProfileMeRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  RoomCreateRoute: RoomCreateRoute,
  RoomWelcomeRoute: RoomWelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
